remote-week2: API practice
AnnYang81/remote-assignment pull request #2
Opened 2023-10-07 15:05 UTC by AnnYang81

**IP address：http://176.34.26.227:3000
Database：database1.cun6hnvwo2mq.ap-northeast-1.rds.amazonaws.com
Changes：**

- Upload assignment1 file:express.js

- Upload index.js and backup.sql (assigment2、3:user related API)

1. 在設計user table 時，我將id設為primary key，使其具有唯一性，之後便能用id當條件去select資料庫中符合的資料。此外name、email、password都設為NOT NULL，因為這些都是必要的資料，created_at則用default預設值為當時的時間。

2. status code是必要的，它是web server回應http請求時的回應代碼，此外也可以透過status code來告知伺服器所遇到的問題，如常見的404就是告知伺服器無法找到此頁面。

3. 使用postman去測試，下圖分別為在postman用post、get測試assignmen3 API的結果。
<img width="600" alt="3-1" src="https://github.com/AnnYang81/remote-assignment/assets/138404005/7d513b22-b007-4eea-a387-6bb8310a1e9f">
<img width="600" alt="3-2" src="https://github.com/AnnYang81/remote-assignment/assets/138404005/a325a3ca-9954-4410-85d8-e96e147b34b3">

4. 使用pm2啟動node.js，確保在執行pm2 stop node.js前，該程序不會中斷。
PS.有用postman測試離開ssh connection後，API依然能正常運作。

5. 
<img width="600" alt="5" src="https://github.com/AnnYang81/remote-assignment/assets/138404005/dc220a65-cdfb-4108-9710-5eaa57095083">

6. 將port值改為process.env.PORT，讓port值根據環境改變，當使用http協議時port=80(HTTPS 協議則port= 443)。在這樣的情況下，瀏覽器會假設你使用http協議，即使省略port(:80)，也會自動解釋為http:/… :80。下圖為實際執行後的結果，即使沒有輸入port，也能成功連接、執行。
<img width="450" alt="withoutport" src="https://github.com/AnnYang81/remote-assignment/assets/138404005/4237935a-4328-4b47-a5c3-ef490f373748">

7. Web server只能處理靜態的內容，如html、影像，而application server可以處理資料庫的存取、business logic。由於Web server不能處理動態內容，因此當他接收到動態內容請求時，會將其傳送給application server做處理，處理完的資料會再傳給Web server，由Web server將內容會應給客戶端。

2023-10-08 14:55 UTC, addie-tyc commented
2. 的部分，其實 status code 不一定需要喔，有些流派就是固定回 200，要解析 body 才會知道錯誤訊息或是得到資料
6. 在 EC2 上把 port 開在 80 有碰到什麼困難嗎？

2023-10-08 15:01 UTC, addie-tyc requested changes
API 現在打不通喔

2023-10-08 15:01 UTC, addie-tyc commented on index.js
> +const bodyParser = require('body-parser');
不確定你用的 express 的版本，但可以確認看看是否仍然需要 body-parser

2023-10-08 15:01 UTC, addie-tyc commented on index.js
> +                    "request-date": new Date().toUTCString()
Request-Date 從 client 送來的 request headers 直接拿就可以囉

2023-10-08 15:50 UTC, AnnYang81 commented on index.js
> +const bodyParser = require('body-parser');
老師好~現在API能使用了( http://176.34.26.227:3000/users )，應該是之前測試完有將它用pm2 stop中斷才導致無法連接。
我使用的express版本是4.18.2，有試過將body-parser刪除，但這樣request中的json資料會無法使用，所以目前還是將它留著。

2023-10-08 16:12 UTC, AnnYang81 commented on index.js
> +                    "request-date": new Date().toUTCString()
了解!
順便回覆老師最上方的問題，我將port設80、確認ec2 instance上輸入規則有設定好後，沒有遇到甚麼問題，下面是我設定port的程式碼。
<img width="252" alt="image" src="https://github.com/AnnYang81/remote-assignment/assets/138404005/042dca0d-0925-4015-8948-624e1ed05918">

2023-10-09 04:29 UTC, addie-tyc requested changes
遇到 fatal error QwQ
<img width="1006" alt="截圖 2023-10-09 12 27 49" src="https://github.com/AnnYang81/remote-assignment/assets/65952631/c6fdd54c-4a03-4d86-9248-edb68931bec2">

healthcheck 打不通
<img width="1009" alt="截圖 2023-10-09 12 28 01" src="https://github.com/AnnYang81/remote-assignment/assets/65952631/62f926b1-4697-4d62-b039-a46eabd75067">

2023-10-10 11:11 UTC, AnnYang81 commented
> 遇到 fatal error QwQ <img alt="截圖 2023-10-09 12 27 49" width="1006" src="https://user-images.githubusercontent.com/65952631/273497958-c6fdd54c-4a03-4d86-9248-edb68931bec2.png">
> 
> healthcheck 打不通 <img alt="截圖 2023-10-09 12 28 01" width="1009" src="https://user-images.githubusercontent.com/65952631/273497976-62f926b1-4697-4d62-b039-a46eabd75067.png">

老師好!我有再重新確認、修改一些地方，可以麻煩老師再幫我測試一次嗎，如果還是無法開啟，我會再預約office hour跟老師討論!(port一樣都是設在3000，分別是http://176.34.26.227:3000/users 和 http://176.34.26.227:3000/healthcheck/)

2023-10-10 15:31 UTC, addie-tyc requested changes

2023-10-10 15:31 UTC, addie-tyc commented on index.js
> +                    "request-date": new Date().toUTCString()
這邊還是沒有從 header 拿對應的 key 喔

2023-10-10 15:31 UTC, addie-tyc commented on index.js
> +    const { id } = req.body;
這邊 parameter 的位置不對呦，題目要求的是 query parameter

2023-10-10 15:31 UTC, addie-tyc commented on index.js
> +                    "request-date": new Date().toUTCString()
一樣可以直接從 header 拿

2023-10-10 16:51 UTC, AnnYang81 commented on index.js
> +                    "request-date": new Date().toUTCString()
已修改成const requestDate = req.headers['request-date'];

2023-10-10 16:52 UTC, AnnYang81 commented on index.js
> +    const { id } = req.body;
已修改成 const id = parseInt(req.query.id, 10);

2023-10-11 01:20 UTC, addie-tyc requested changes
又壞了 QwQ
<img width="1012" alt="截圖 2023-10-11 09 19 33" src="https://github.com/AnnYang81/remote-assignment/assets/65952631/9498a62b-15e6-428e-b3e3-e3535511face">

2023-10-11 01:29 UTC, AnnYang81 commented
> 又壞了 QwQ <img alt="截圖 2023-10-11 09 19 33" width="1012" src="https://user-images.githubusercontent.com/65952631/274113005-9498a62b-15e6-428e-b3e3-e3535511face.png">

我剛剛修好了!!!

2023-10-11 06:27 UTC, addie-tyc requested changes
剩最後一個問題，他說找不到應該要存在的 user XD
<img width="1015" alt="截圖 2023-10-11 14 26 40" src="https://github.com/AnnYang81/remote-assignment/assets/65952631/5f5bce54-7b70-4ac8-a307-ee4b8d46c674">
<img width="1004" alt="截圖 2023-10-11 14 26 52" src="https://github.com/AnnYang81/remote-assignment/assets/65952631/0a5608a9-1887-41d9-a8ff-aed3ea587bd2">

2023-10-11 07:34 UTC, AnnYang81 commented
@addie-tyc 改好了!! 麻煩老師了，我下次會仔細看題目!

2023-10-11 09:13 UTC, addie-tyc approved these changes
LGTM

2023-10-12 06:09 UTC, merged